-- ============================================================
-- access_token — ACCOUNT-level credentials for API and MCP authentication.
--
-- There are now exactly TWO credential types in this product, and they are opposites. Keeping
-- the distinction sharp is the point of this migration:
--
--   app_key (003)      PUBLIC.  Per-app. Plaintext in the database, printed in the dashboard,
--                      embedded in the consumer's SOURCE CODE and shipped inside the client
--                      binary. Anyone can extract it from an APK. Hashing it would protect
--                      nothing while preventing a developer from reading the key their own app
--                      already contains. What protects it is BINDING — applicationId, cert
--                      digest, environment — not secrecy.
--
--   access_token (016) SECRET.  Per-USER. Acts as its owner across every app they can reach:
--                      it can register apps, mint publishable keys, change parameters and
--                      publish. It is stored as a SHA-256 HASH and shown exactly once at
--                      creation. A database leak must not yield a usable credential.
--
-- Confusing the two in either direction is a real failure: treating the publishable key as
-- secret adds friction that buys nothing, and treating the access token as public hands over
-- the account.
-- ============================================================

-- `rcp_` = rconfig personal, by analogy with Supabase's `sbp_`. Deliberately NOT `rck_`
-- (003's publishable prefix): the two must be distinguishable at a glance in a log, a shell
-- history or a support ticket, because the correct reaction to seeing one in public differs
-- completely.
--
-- 40 chars of base62 ≈ 238 bits. Generated by REJECTION SAMPLING for the reason 003 explains
-- and this function actually depends on: `% 62` over 256 makes the first 8 alphabet characters
-- ~25% likelier, which for a credential that IS secret is a genuine reduction in entropy
-- rather than a cosmetic one.
CREATE OR REPLACE FUNCTION public.generate_access_token() RETURNS text
LANGUAGE plpgsql VOLATILE AS $$
DECLARE
  alphabet text := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  out text := '';
  b int;
BEGIN
  WHILE length(out) < 40 LOOP
    b := get_byte(gen_random_bytes(1), 0);
    IF b < 248 THEN                       -- 248 = 4*62; discard the uneven tail
      out := out || substr(alphabet, 1 + (b % 62), 1);
    END IF;
  END LOOP;
  RETURN 'rcp_' || out;
END $$;

CREATE TABLE IF NOT EXISTS public.access_token (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name          text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 80),

    -- sha256 hex of the plaintext. UNIQUE so verification is an index probe rather than a
    -- scan, and so a collision surfaces as an error instead of an ambiguous identity.
    token_hash    text NOT NULL UNIQUE,

    -- The first 16 characters ("rcp_" + 12), stored so the dashboard can show WHICH token a
    -- row is without being able to reconstruct it. 12 random base62 chars ≈ 71 bits — enough
    -- to tell tokens apart, nowhere near enough to guess the remaining 28.
    token_prefix  text NOT NULL,

    -- NULL = every app the owner can reach, re-evaluated at verify time. A token scoped to
    -- the empty set would be useless, so NULL is "unscoped" rather than a sentinel row.
    -- Scoped tokens get rows in access_token_app.
    scoped        boolean NOT NULL DEFAULT false,

    permissions   text[] NOT NULL DEFAULT ARRAY['read']::text[],

    expires_at    timestamptz,
    last_used_at  timestamptz,
    revoked_at    timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS access_token_user_idx ON public.access_token(user_id);

CREATE TABLE IF NOT EXISTS public.access_token_app (
    token_id  uuid NOT NULL REFERENCES public.access_token(id) ON DELETE CASCADE,
    app_id    uuid NOT NULL REFERENCES public.app(id) ON DELETE CASCADE,
    PRIMARY KEY (token_id, app_id)
);

ALTER TABLE public.access_token     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_token_app ENABLE ROW LEVEL SECURITY;

-- A user sees only their OWN tokens. Note there is no policy granting SELECT on token_hash to
-- anyone in particular — the column is readable by the owner, which is harmless: it is a hash,
-- and its owner already held the plaintext once.
CREATE POLICY access_token_own ON public.access_token FOR ALL TO authenticated
    USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY access_token_app_own ON public.access_token_app FOR ALL TO authenticated
    USING (EXISTS (SELECT 1 FROM public.access_token t WHERE t.id = token_id AND t.user_id = auth.uid()))
    WITH CHECK (EXISTS (SELECT 1 FROM public.access_token t WHERE t.id = token_id AND t.user_id = auth.uid()));

GRANT SELECT, DELETE ON public.access_token     TO authenticated;
GRANT SELECT, DELETE ON public.access_token_app TO authenticated;

-- ============================================================
-- access_token_create — mint a token and return the plaintext ONCE.
--
-- The plaintext is returned to the caller and never persisted. There is deliberately no
-- "reveal" path: a token the dashboard could re-display would be a token stored in a form the
-- database could leak.
-- ============================================================
CREATE OR REPLACE FUNCTION public.access_token_create(
    p_user_id         uuid,
    p_name            text,
    p_expires_in_days int     DEFAULT 30,
    p_app_ids         uuid[]  DEFAULT NULL,
    p_permissions     text[]  DEFAULT ARRAY['read']::text[]
) RETURNS TABLE (id uuid, token text)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE
  v_token text;
  v_id    uuid;
  v_app   uuid;
  v_bad   text;
BEGIN
  -- A closed permission set, checked here rather than by a CHECK constraint so the error names
  -- the offending value. An unknown permission silently stored would be an authorization
  -- decision nobody made.
  SELECT x INTO v_bad FROM unnest(p_permissions) AS x
   WHERE x NOT IN ('read','write','publish') LIMIT 1;
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'unknown permission: %. Valid: read, write, publish', v_bad
      USING ERRCODE = '22023';
  END IF;

  IF p_expires_in_days IS NOT NULL AND p_expires_in_days <= 0 THEN
    RAISE EXCEPTION 'expires_in_days must be positive, got %', p_expires_in_days
      USING ERRCODE = '22023';
  END IF;

  -- Scoping is only meaningful if it cannot be claimed over apps the owner has no business
  -- reaching. Without this check a user could name any uuid and the token would assert it —
  -- the scope would describe an intention rather than a boundary.
  IF p_app_ids IS NOT NULL THEN
    FOREACH v_app IN ARRAY p_app_ids LOOP
      IF NOT EXISTS (
        SELECT 1 FROM public.app_member m
         WHERE m.app_id = v_app AND m.user_id = p_user_id
      ) AND NOT EXISTS (
        SELECT 1 FROM public.app a WHERE a.id = v_app AND a.owner_id = p_user_id
      ) THEN
        RAISE EXCEPTION 'cannot scope a token to app % — its owner is not a member', v_app
          USING ERRCODE = '42501';
      END IF;
    END LOOP;
  END IF;

  v_token := public.generate_access_token();

  INSERT INTO public.access_token (user_id, name, token_hash, token_prefix, scoped, permissions, expires_at)
  VALUES (
    p_user_id,
    trim(p_name),
    encode(digest(v_token, 'sha256'), 'hex'),
    substr(v_token, 1, 16),
    p_app_ids IS NOT NULL,
    p_permissions,
    CASE WHEN p_expires_in_days IS NULL THEN NULL
         ELSE now() + make_interval(days => p_expires_in_days) END
  )
  RETURNING access_token.id INTO v_id;

  IF p_app_ids IS NOT NULL THEN
    INSERT INTO public.access_token_app (token_id, app_id)
    SELECT v_id, unnest(p_app_ids);
  END IF;

  RETURN QUERY SELECT v_id, v_token;
END $$;

-- ============================================================
-- access_token_verify — resolve a presented token to an identity and a scope.
--
-- Returns ZERO ROWS for anything that is not a live token: unknown, malformed, revoked or
-- expired. One shape for every failure is deliberate — a caller that could distinguish
-- "expired" from "never existed" is an oracle for probing which tokens are real.
-- ============================================================
CREATE OR REPLACE FUNCTION public.access_token_verify(p_token text)
RETURNS TABLE (token_id uuid, user_id uuid, permissions text[], app_ids uuid[])
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE
  v_hash text;
  v_rec  record;
BEGIN
  IF p_token IS NULL OR p_token !~ '^rcp_[A-Za-z0-9]{40}$' THEN
    RETURN;                              -- malformed: no rows, no error, no detail
  END IF;

  v_hash := encode(digest(p_token, 'sha256'), 'hex');

  SELECT t.id, t.user_id, t.permissions, t.scoped
    INTO v_rec
    FROM public.access_token t
   WHERE t.token_hash = v_hash
     AND t.revoked_at IS NULL
     AND (t.expires_at IS NULL OR t.expires_at > now());

  IF NOT FOUND THEN
    RETURN;
  END IF;

  -- Stamped on every verification, so the dashboard's "last used" is a fact rather than
  -- decoration — it is how an operator tells a token in daily use from one nobody can account
  -- for, which is the first question asked when deciding what is safe to revoke.
  UPDATE public.access_token SET last_used_at = now() WHERE access_token.id = v_rec.id;

  RETURN QUERY
  SELECT
    v_rec.id,
    v_rec.user_id,
    v_rec.permissions,
    CASE WHEN NOT v_rec.scoped THEN NULL
         ELSE (SELECT array_agg(ta.app_id ORDER BY ta.app_id)
                 FROM public.access_token_app ta WHERE ta.token_id = v_rec.id)
    END;
END $$;

-- ============================================================
-- access_token_revoke — immediate and irreversible.
-- ============================================================
CREATE OR REPLACE FUNCTION public.access_token_revoke(p_id uuid, p_user_id uuid)
RETURNS void
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public, extensions AS $$
DECLARE
  v_owner uuid;
BEGIN
  SELECT user_id INTO v_owner FROM public.access_token WHERE id = p_id;
  IF v_owner IS NULL THEN
    RAISE EXCEPTION 'no such token' USING ERRCODE = '42501';   -- same error as "not yours":
  END IF;                                                       -- existence is not disclosed
  IF v_owner <> p_user_id THEN
    RAISE EXCEPTION 'that token belongs to another user' USING ERRCODE = '42501';
  END IF;
  UPDATE public.access_token SET revoked_at = now() WHERE id = p_id AND revoked_at IS NULL;
END $$;

-- `authenticated` may mint and revoke THEIR OWN (the functions take the user id and the
-- dashboard passes auth.uid()). verify is NOT granted to authenticated or anon: it is an
-- authentication primitive for the privileged API process, and exposing it to the public role
-- would turn it into a token-probing oracle.
GRANT EXECUTE ON FUNCTION public.access_token_create(uuid, text, int, uuid[], text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.access_token_revoke(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_access_token() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.access_token_verify(text) FROM PUBLIC, anon, authenticated;
